# 头部菜单，title: link
menu:
  Blog: https://www.acdiost.cc
  Github: https://github.com/acdiost
  Twitter: https://twitter.com/acdiost
  分类: /categories
  归档: /archives
  标签云: /tags
  Mint杂货铺: https://store.acdiost.cn
  Hexo: https://hexo.io

# 是否显示目录
TOC: true

# 是否自动播放音乐
autoplay: false

# 默认音乐（随机播放）
mp3: 
  - http://link.hhtjim.com/163/32835377.mp3
  - http://link.hhtjim.com/qq/001faIUs4M2zna.mp3
  - https://link.hhtjim.com/163/2658203.mp3

# 首页封面图, 为空时取文章的cover作为封面(注意跨域问题,建议使用同源图片)
welcome_cover: # /img/welcome-cover.jpg

# 默认文章封面图（随机调用,支持外链）
cover: /img/cover.jpg

# 是否使用mathjax
mathjax: false

# 是否关闭默认滚动条
scrollbar: true

# 本地搜索,请将索引文件放在网站根目录,或修改主题js文件的path值
local_search:
    # 是否启用
    enable: false

# 是否显示 一言(hitokoto)
hitokoto: true

# 链接(可选:facebook,twitter,github,wechat,email)
links:
    facebook: https://facebook.com/acdiost
    twitter: https://twitter.com/acdiost
    github: https://github.com/acdiost
    wechat: /
    email: mailto:acdiost@gmail.com
  
# 备案
beian: 
    # 是否显示备案信息
    enable: false
    # 是否在主页面最底下显示备案信息(虽然丑，但是完全满足规定要求)
    enableFooter: false
    # 备案号
    beianInfo: ICP备xxxxxxx号
    # 链接地址
    link: http://www.beian.miit.gov.cn

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否启用评论功能
    enable: true
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: '80c0a1731898dd4dd04f'
    # 应用秘钥
    clientSecret: '20ef950e67a9b95b6698b227c0717df682a83803'
    # issue仓库名
    repo: 'acdiost.github.io'
    # Github名
    owner: 'acdiost'
    # Github名
    admin: ['acdiost']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: acdiost,dawn

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
